### PR TITLE
Add the Formattable section to the spec

### PR DESCRIPTION
**Pull request by eemeli**
As the proposal's text describes, a `Formattable` is a wrapper around values and their formatting options. It may be thought of as an abstraction that allows us to define the rest of the specification in a manner that's independent of the actual type of any runtime value.

The text briefly refers to MessageFormatParts. The section defining them has not yet been submitted for review, but some relevant discussion may be found in issue #41. Similarly, while PatternElements are also referred to in the preceding PR #195, they are not yet in the spec. Relevant discussion may be found in #190, which also includes some consideration of Formattables.

In the `third` proposal by @stasm, a corresponding abstraction uses the name `RuntimeValue`.

### CODE REVIEW

**Comment by mihnita** [comment]
I think we are talking about this in https://github.com/unicode-org/message-format-wg/pull/190 ?
So maybe let's not "fork" the discussion and confuse things?

**Comment by eemeli** [comment]
@mihnita While the discussion in #190 does also cover Formattables, that should not preclude a review of this particular PR.

**Review by mihnita — CHANGES_REQUESTED** [review]
> @mihnita While the discussion in #190 does also cover Formattables, that should not preclude a review of this particular PR.

It does, because it is not clear at all that this concept is even needed.
And even less what it looks like.

**Comment by eemeli** [comment]
Closing as out of date after #307.

**Pull request closed without merging**
