### PR TITLE
Bringing the spec description in sync with the abnf

### PR DESCRIPTION
**Pull request by mihnita**
The `.abnf` is now this:
```
variable = "$" name
function = (":" / "+" / "-") name
```

In `{b :html}` the `:html` is the function, not `b` (similar to `{43 :number}` and `{|20231217T1930| :datetime}`)

### CODE REVIEW

**Comment by aphillips** [comment]
You're not wrong. Note the changes in #441 and the move towards defining standalone/opening/closing "elements", which should properly be termed _expression_.

**Comment by mihnita** [comment]
> Note the changes in #441

If it helps with the refactoring you are trying to do I can either delay this until after you land #441, or you can make the change directly in #441.

**Comment by eemeli** [comment]
I think this is blocked by #441, and I'd really rather not introduce further increases to its scope from its current rather massive extent, but discuss changes like this after that PR has been merged.

**Comment by aphillips** [comment]
Per teleconference, please refector to fit in the syntax.md file and then ping me to merge.

**Review by eemeli — CHANGES_REQUESTED** [review]
As discussed on prior meetings, this PR should be rebased on the latest `main` for further consideration.

**Comment by mihnita** [comment]
Replaced by #466
This one was too messy to merge. And was done in my main, making it worse.

**Pull request closed without merging**
