### PR TITLE
Add docs/design/, with accepted & rejected design documents

### PR DESCRIPTION
**Pull request by eemeli**
Context: #523

This moves the accepted & rejected design docs to a more likely location under `docs/design/`, and fixes their titles & metadata. A README is added to that folder.

[Delimiting of Patterns in Complex Messages](https://github.com/unicode-org/message-format-wg/blob/main/exploration/delimiting-variant-patterns.md) is left in `exploration/`. Even though it's marked as "Accepted", it does not contain a description of the selected design. Its previous status of "Balloting" was updated in #559.

### CODE REVIEW

**Comment by aphillips** [comment]
Please don't move the documents.

**Comment by aphillips** [comment]
In the 2024-01-29 call we agreed not to merge this specific PR. Create new PRs as needed to clean up design docs or to move them.

**Comment by eemeli** [comment]
Reopening, as suggested in https://github.com/unicode-org/message-format-wg/issues/523#issuecomment-1881247040.

**Comment by aphillips** [comment]
Closing again, as we're maintaining differently. We can discuss changing management of design documents in an issue if needed.

**Pull request closed without merging**
