### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by srl295**
site-wide updates per https://github.com/unicode-org/.github/issues/17

### CODE REVIEW

**Review by eemeli — CHANGES_REQUESTED** [review]
This repo's CONTRIBUTING.md also includes a section on "Joining the Working Group" that would be lost by linking to the org-level document.

**Comment by aphillips** [comment]
@eemeli is not wrong, although this page also has similar instructions. We should:

1. Merge this.
2. Change our CONTRIBUTING.md to point to the Unicode version (in a separate PR that I will initiate)
3. Fix the joining instructions in this page

The joining instructions need to be updated in any event.

**Review by aphillips — APPROVED** [review]

**Comment by srl295** [comment]
> This repo's CONTRIBUTING.md also includes a section on "Joining the Working Group" that would be lost by linking to the org-level document.

I missed this, thanks.

**Comment by srl295** [comment]
@eemeli take a look now

**Review by eemeli — APPROVED** [review]

**Pull request merged**
