### PR TITLE
Create notes-2020-05-18.md

### PR DESCRIPTION
**Pull request by romulocintra**

### CODE REVIEW

**Comment by romulocintra** [comment]
cc @nbouvrette in case you want to help Pablo upload the meeting notes please find here already a draft PR

**Comment by nbouvrette** [comment]
> cc @nbouvrette in case you want to help Pablo upload the meeting notes please find here already a draft PR

@romulocintra I still seem to have missing access - I got the file ready whenever I can push it :)

**Comment by romulocintra** [comment]
> cc @nbouvrette in case you want to help Pablo upload the meeting notes please find here already a draft PR

I assigned this PR to you , if you can try again ...

**Comment by nbouvrette** [comment]
Push failed Remote: Permission to unicode-org/message-format-wg.git denied to nbouvrette. unable to access 'https://github.com/unicode-org/message-format-wg.git/': The requested URL returned error: 403

**Pull request merged**
